<template>
    <div class="post">
        <div v-if="postDTO.titleImg" class="img-wrapper">
            <router-link :to="{name: post, params: { id: postDTO.id} }"><img :src="postDTO.titleImg"/></router-link>
        </div>
        <div class="text-wrapper">
            <div class="post-head">
                <router-link :to="{name: post, params: { id: postDTO.id} }"><h2 v-html="postDTO.title"></h2></router-link>
                <owner v-if="postDTO.owner" :owner="postDTO.owner" :createTime="createTime" :editTime="editTime"></owner>
                <span v-if="postDTO.commentCount" class="comment-counter">{{postDTO.commentCount}} comments</span>
            </div>
            <!-- Html used for highlight search results. Html tags are generated by fulltext search engine. -->
            <div class="post-content" v-html="postDTO.text"></div>
        </div>
        <hr size="1"/>
    </div>
</template>

<script>
    import {post} from '../routes';
    import Owner from './Owner.vue'
    import {getTimestampFromUtc} from '../utils'

    export default {
        name: 'post-item',
        props: ['postDTO'], // it may be an object, for ability to set default values
        data() {
            return {
                post: post
            }
        },
        components:{
            Owner
        },
        computed:{
            createTime(){
                return this.postDTO.createDateTime ? getTimestampFromUtc(this.postDTO.createDateTime) : null;
            },
            editTime(){
                return this.postDTO.editDateTime ? getTimestampFromUtc(this.postDTO.editDateTime) : null;
            }
        },
    }
</script>

<style lang="stylus" scoped>
    @import "../constants.styl"
    $borderColor=red;
    $imgMaxHeight=200px
    $imgMaxWidth=400px
    .post {
        display block
        // border-style solid
        border-width 1px;
        border-color $borderColor
        padding 2px;
        margin 2px;
        //clear: both

        .img-wrapper {
            // max-height 400px;
            // clear both
            img {
                float: left
                margin 10px;
                //width: 350px;
                // display inline
                // height: auto;
                //max-height 400px;
                max-height $imgMaxHeight
                max-width $imgMaxWidth
                border-radius 2px
                box-shadow: 0 4px 8px 4px rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            }

        }

        .text-wrapper {
            min-height 100px
            max-height 600px;
            font-size $postBodyFontSize
            font-family $postBodyFontFamily

            .post-head{
                display flex
                flex-direction row
                //justify-content space-between
                flex-wrap wrap
            }

            a {
                text-decoration: none;
                h2 {
                    padding 2px;
                    margin 2px;
                    color $postTitleColorLink
                    font-size $postTitleFontSize
                    font-weight $postTitleFontWeight
                    font-family $postTitleFontFamily

                    u {
                        color red
                    }

                }
            }

        }

        .comment-counter {
            display flex
            flex-direction row
            align-items center
            flex-wrap wrap
            color white

            justify-content center
            background-color #C21F39
            border-radius 2px
            padding 2px 8px
        }

        hr {
            clear both
            color lightgrey
        }
    }

    @media screen and (max-width: $contentWidth) {
        .post {
            .img-wrapper {
                img {
                    float: none
                    margin 0px;
                    // margin 4px;
                    width 100%
                    height 100%
                    box-shadow: none
                    max-height 100%
                    max-width 100%
                }
                img:hover {
                    transform none
                    box-shadow: none
                    transition none
                }
            }

            .text-wrapper {
                max-height none

                .post-content {
                    overflow-x auto
                }
            }

        }
    }
</style>