<template>
    <div class="post">
        <div class="img-wrapper">
            <img :src="postDTO.titleImg"/>
        </div>
        <div class="text-wrapper">
            <div class="post-head">
                <router-link :to="{name: post, params: { id: postDTO.id} }"><h2 v-html="postDTO.title"></h2></router-link>
                <owner v-if="postDTO.owner" prepend="written by" :owner="postDTO.owner" :time="createTime"></owner>
            </div>
            <!-- Html used for highlight search results. Html tags are generated by fulltext search engine. -->
            <div class="post-content" v-html="postDTO.text"></div>
        </div>
        <hr/>
    </div>
</template>

<script>
    import {post} from '../routes';
    import Owner from './Owner.vue'
    import {getTimestampFromUtc} from '../utils'

    export default {
        name: 'post-item',
        props: ['postDTO'], // it may be an object, for ability to set default values
        data() {
            return {
                post: post
            }
        },
        components:{
            Owner
        },
        computed:{
            createTime(){
                return getTimestampFromUtc(this.postDTO.createDateTime);
            }
        },
    }
</script>

<style lang="stylus" scoped>
    @import "../constants.styl"
    $borderColor=red;
    $imgMaxHeight=200px
    .post {
        display block
        // border-style solid
        border-width 1px;
        border-color $borderColor
        padding 2px;
        margin 2px;
        //clear: both

        .img-wrapper {
            // max-height 400px;
            // clear both
            img {
                float: left
                margin 10px;
                width: 250px;
                // display inline
                // height: auto;
                //max-height 400px;
                max-height $imgMaxHeight
            }
        }

        .text-wrapper {
            //clear: both
            // height auto
            // float: right;
            min-height 100px
            max-height 600px;

            .post-head{
                display flex
                flex-direction row
                //justify-content space-between
                flex-wrap wrap
            }

            a {
                text-decoration: none;
                h2 {
                    padding 2px;
                    margin 2px;
                    color blue

                    u {
                        color red
                    }

                }
            }

        }

        hr {
            clear both
        }
    }

    @media screen and (max-width: $contentWidth) {
        .post {
            .img-wrapper {
                img {
                    float: none
                    margin 0px;
                    // margin 4px;
                    width auto
                    max-width 100%
                    max-height 500px
                }
            }

            .post-content {
                overflow-x auto
            }

        }
    }
</style>